---
- name: Make sure the ip_forward kernel flag is enabled very boot.
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/99-sysctl.conf
    line: 'net.ipv4.ip_forward=1'
    insertafter: EOF
    state: present
  notify: Make sure the ip_forward is enabled
  become: true

- name: Ensure wireguard is installed.
  ansible.builtin.apt:
    pkg:
      - wireguard
      - iptables
    state: present
  become: true

- name: Check if the wireguard is configured.
  ansible.builtin.stat:
    path: /etc/wireguard/wg0.conf
  register: wg
  become: true

- name: Include wireguard config tasks.
  ansible.builtin.include_tasks: wg0_config.yml
  when: wg.stat.exists is false

- name: Starts the wg0 link.
  ansible.builtin.command:
    cmd: wg-quick up wg0
  register: wg_up
  changed_when: '"already exists" not in wg_up.stderr'
  failed_when: >
    (wg_up.rc != 0) and
    ("already exists" not in wg_up.stderr)
  become: true

- name: Ensures the wg-quick@wg0.service is enabled.
  ansible.builtin.systemd:
    name: wg-quick@wg0.service
    enabled: true
  become: true
