---
- name: Ensure all databases are created.
  community.postgresql.postgresql_db:
    name: "{{ item.name }}"
    login_user: "{{ postgres['admin_user'] }}"
    login_password: "{{ postgres['admin_passwd'] }}"
    maintenance_db: "{{ postgres['admin_db'] }}"
    login_host: "{{ containers['loopback_network_address'] }}"
    port: 5432
    template: template0
    encoding: "UTF8"
    state: present
  loop:
    - { name: "{{ keycloak['db_name'] }}", enabled: "{{ keycloak['enabled'] }}" }
    - { name: "{{ mailu['db_name'] }}", enabled: "{{ mailu['enabled'] }}" }
    - { name: "{{ mailu['roundcube']['db_name'] }}",
        enabled: "{{ mailu['roundcube']['enabled'] and mailu['enabled'] }}" }
    - { name: "{{ nextcloud['db_name'] }}", enabled: "{{ nextcloud['enabled'] }}" }
  when: item.enabled|bool

- name: Ensure all database users are created.
  community.postgresql.postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    login_user: "{{ postgres['admin_user'] }}"
    login_password: "{{ postgres['admin_passwd'] }}"
    db: "{{ postgres['admin_db'] }}"
    login_host: "{{ containers['loopback_network_address'] }}"
    port: 5432
    no_password_changes: true
    state: present
  environment:
    PGOPTIONS: "-c password_encryption=scram-sha-256"
  loop:
    - { name: "{{ keycloak['postgres_user'] }}", password: "{{ keycloak['postgres_password'] }}",
        enabled: "{{ keycloak['enabled'] }}" }
    - { name: "{{ mailu['postgres_user'] }}", password: "{{ mailu['postgres_password'] }}",
        enabled: "{{ mailu['enabled'] }}" }
    - { name: "{{ mailu['roundcube']['postgres_user'] }}",
        password: "{{ mailu['roundcube']['postgres_password'] }}",
        enabled: "{{ mailu['roundcube']['enabled'] and mailu['enabled'] }}" }
    - { name: "{{ nextcloud['postgres_user'] }}", password: "{{ nextcloud['postgres_password'] }}",
        enabled: "{{ nextcloud['enabled'] }}" }
  when: item.enabled|bool

- name: Change database owners to their respective users if they don't have it yet.
  community.postgresql.postgresql_owner:
    db: "{{ item.db }}"
    obj_name: "{{ item.obj_name }}"
    new_owner: "{{ item.new_owner }}"
    login_user: "{{ postgres['admin_user'] }}"
    login_password: "{{ postgres['admin_passwd'] }}"
    login_host: "{{ containers['loopback_network_address'] }}"
    port: 5432
    obj_type: database
  loop:
    - { db: "{{ keycloak['db_name'] }}", obj_name: "{{ keycloak['db_name'] }}",
        new_owner: "{{ keycloak['postgres_user'] }}", enabled: "{{ keycloak['enabled'] }}" }
    - { db: "{{ mailu['db_name'] }}", obj_name: "{{ mailu['db_name'] }}",
        new_owner: "{{ mailu['postgres_user'] }}", enabled: "{{ mailu['enabled'] }}" }
    - { db: "{{ mailu['roundcube']['db_name'] }}", obj_name: "{{ mailu['roundcube']['db_name'] }}",
        new_owner: "{{ mailu['roundcube']['postgres_user'] }}",
        enabled: "{{ mailu['roundcube']['enabled'] }}" }
    - { db: "{{ nextcloud['db_name'] }}", obj_name: "{{ nextcloud['db_name'] }}",
        new_owner: "{{ nextcloud['postgres_user'] }}", enabled: "{{ nextcloud['enabled'] }}" }
  when: item.enabled|bool

- name: Grant database to their respective users if they don't have it yet.
  community.postgresql.postgresql_privs:
    database: "{{ item.db }}"
    roles: "{{ item.roles }}"
    login_user: "{{ postgres['admin_user'] }}"
    login_password: "{{ postgres['admin_passwd'] }}"
    login_host: "{{ containers['loopback_network_address'] }}"
    port: 5432
    privs: all
    grant_option: false
    type: database
    state: present
  loop:
    - { db: "{{ keycloak['db_name'] }}", roles: "{{ keycloak['postgres_user'] }}",
        enabled: "{{ keycloak['enabled'] }}" }
    - { db: "{{ mailu['db_name'] }}", roles: "{{ mailu['postgres_user'] }}",
        enabled: "{{ mailu['enabled'] }}" }
    - { db: "{{ mailu['roundcube']['db_name'] }}", roles: "{{ mailu['roundcube']['postgres_user'] }}",
        enabled: "{{ mailu['roundcube']['enabled'] }}" }
    - { db: "{{ nextcloud['db_name'] }}", roles: "{{ nextcloud['postgres_user'] }}",
        enabled: "{{ nextcloud['enabled'] }}" }
  when: item.enabled|bool
