---
- name: Main playbook.
  hosts: all

  vars_files:
    user_vars.yaml

  roles:
    - role: roles/playbook_vars/

    - role: roles/system/basic/

    - role: roles/system/vim
      when: optional_roles['vim']

    - role: roles/system/zsh
      when: optional_roles['zsh']

    - role: roles/system/container_setup/

    - role: roles/containers/infra/postgres/
