---
- name: Make sure the dovecot container is running.
  community.docker.docker_container:
    name: dovecot
    image: "ghcr.io/mailu/dovecot:{{ mailu['container_version'] }}"
    networks:
      - name: container-network
    dns_servers: "{{ mailu_dns }}"
    etc_hosts: "{{ containers_etc_hosts }}"
    ports:
      - "{{ containers['loopback_network_address'] }}:10152:143"
      - "{{ containers['loopback_network_address'] }}:10153:110"
      - "{{ containers['loopback_network_address'] }}:10154:4190"
    mounts:
      - # mailu dir
        source: "{{ containers['data_dir'] }}/mailu/mail/"
        target: /mail
        type: bind
    state: started
    restart_policy: unless-stopped
    env_file: "{{ containers['config_dir'] }}/mailu/mailu.env"
    docker_host: unix:///run/user/{{ ansible_user_uid }}/docker.sock
