---
- name: Make sure the fetchmail container is running.
  community.docker.docker_container:
    name: fetchmail
    image: "mailu/fetchmail:{{ mailu['container_version'] }}"
    user: '1300:1300'
    networks:
      - name: container-network
    dns_servers: "{{ mailu_dns }}"
    etc_hosts: "{{ containers_etc_hosts }}"
    mounts:
      - # fetchmail dir
        source: "{{ containers['data_dir'] }}/mailu/fetchmail"
        target: /data
        type: bind
    state: started
    restart_policy: unless-stopped
    env_file: "{{ containers['config_dir'] }}/mailu/mailu.env"
    docker_host: unix:///run/user/{{ ansible_user_uid }}/docker.sock
