---
- name: Inspect the mailu-admin image.
  community.docker.docker_image_info:
    name: mailu/admin:v2.0.10
    docker_host: unix:///run/user/{{ ansible_user_uid }}/docker.sock
  register: mailu_admin

- name: Include mailu-admin image build tasks if necessary.
  ansible.builtin.include_tasks: mailu_admin_img.yml
  when: mailu_admin.images | length == 0

- name: Make sure the mailu-admin container is running.
  community.docker.docker_container:
    name: mailu-admin
    image: mailu/admin:v2.0.10
    networks:
      - name: container-network
    dns_servers: "{{ mailu_dns }}"
    etc_hosts: "{{ containers_etc_hosts }}"
    ports: "{{ containers['loopback_network_address'] }}:10102:80"
    mounts:
      - # mailu dir
        source: "{{ containers['data_dir'] }}/mailu/mail/data"
        target: /data
        type: bind
      - # dkim dir
        source: "{{ containers['data_dir'] }}/mailu/mail/dkim"
        target: /dkim
        type: bind
    log_driver: journald
    log_options:
      tag: mailu-admin
    state: started
    restart_policy: unless-stopped
    env_file: "{{ containers['config_dir'] }}/mailu/mailu.env"
    docker_host: unix:///run/user/{{ ansible_user_uid }}/docker.sock
