---
- name: Make sure the postfix container is running.
  community.docker.docker_container:
    name: postfix
    image: "mailu/postfix:{{ mailu['container_version'] }}"
    networks:
      - name: container-network
    dns_servers: "{{ mailu_dns }}"
    etc_hosts: "{{ containers_etc_hosts }}"
    ports:
      - "{{ containers['loopback_network_address'] }}:10150:25"
      - "{{ containers['loopback_network_address'] }}:10151:10025"
    mounts:
      - # mailqueue dir
        source: "{{ containers['data_dir'] }}/mailu/mailqueue"
        target: /queue
        type: bind
    state: started
    restart_policy: unless-stopped
    env_file: "{{ containers['config_dir'] }}/mailu/mailu.env"
    docker_host: unix:///run/user/{{ ansible_user_uid }}/docker.sock
