---
- name: Make sure the rspamd container is running.
  community.docker.docker_container:
    name: rspamd
    image: "ghcr.io/mailu/rspamd:{{ mailu['container_version'] }}"
    networks:
      - name: container-network
    dns_servers: "{{ mailu_dns }}"
    etc_hosts: "{{ containers_etc_hosts }}"
    ports: "{{ containers['loopback_network_address'] }}:11334:11334"
    mounts:
      - # filter dir
        source: "{{ containers['data_dir'] }}/mailu/filter"
        target: /var/lib/rspamd
        type: bind
    state: started
    restart_policy: unless-stopped
    env_file: "{{ containers['config_dir'] }}/mailu/mailu.env"
    docker_host: unix:///run/user/{{ ansible_user_uid }}/docker.sock
