---
- name: Create email used by other services user.
  community.docker.docker_container_exec:
    container: mailu-admin
    command: flask mailu user {{ mailu['services_mail']['username'] }}
      {{ mailu['mail_domain'] }} "{{ mailu['services_mail']['password'] }}"
    docker_host: unix:///run/user/{{ ansible_user_uid }}/docker.sock
  register: exec_output
  changed_when: exec_output.rc == 0
  failed_when: >
    (exec_output.rc != 0) and
    (' already exists.' not in exec_output.stderr)
