---
- name: Update the cache if needed.
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Ensures the systemd networkd is enabled.
  ansible.builtin.systemd:
    name: systemd-networkd.service
    enabled: true
  become: true

- name: Set server timezone.
  community.general.timezone:
    name: "{{ server['timezone'] }}"
  become: true

- name: Make /etc/hosts is updated with all domain names.
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ server['network']['ipv4'] }} {{ ssl_domains_list | flatten | join(' ') }}"
    insertafter: EOF
    state: present
  become: true
  when: ssl_domains_list is defined
