---
- name: Update the cache if needed.
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Ensures the systemd networkd is enabled.
  ansible.builtin.systemd:
    name: systemd-networkd.service
    enabled: true
  become: true
  when: >
    dns['enabled'] or
    homer['enabled'] or
    keycloak['enabled'] or
    mailu['enabled'] or
    nextcloud['enabled']

- name: Set server timezone.
  community.general.timezone:
    name: "{{ server['timezone'] }}"
  become: true

- name: Make /etc/hosts is updated with all domain names.
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ server['network']['ipv4'] }} {{ ssl_domains_list | flatten | join(' ') }}"
    insertafter: EOF
    state: present
  become: true
  when: ssl_domains_list is defined

- name: Ensures the user's systemd folder is inplace.
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/systemd/user"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory
    mode: 0740
  when: >
    nginx_proxy['certbot']['enabled'] is true or
    nextcloud['enabled'] is true

- name: Ensure systemd-timesyncd is installed.
  ansible.builtin.apt:
    pkg: systemd-timesyncd
    state: present
  become: true

- name: Ensures the systemd-timesyncd is enabled.
  ansible.builtin.systemd:
    name: systemd-timesyncd.service
    enabled: true
  become: true

- name: Ensure git is installed.
  ansible.builtin.apt:
    pkg: git
    state: present
  become: true
  when: mailu['enabled'] is true
