---
- name: Create or update a Keycloak nextcloud client.
  community.general.keycloak_client:
    ######## Authentication credentials ########
    auth_client_id: admin-cli
    auth_keycloak_url: https://accounts.{{ server['network']['domain_name'] }}
    validate_certs: "{{ nginx_proxy['certbot']['enabled'] }}"
    auth_username: "{{ keycloak['admin'] }}"
    auth_password: "{{ keycloak['admin_password'] }}"
    auth_realm: master
    realm: "{{ keycloak['realm_name'] }}"
    ######## General Settings ########
    enabled: true
    client_id: "{{ nextcloud['OIDC']['client_id'] }}"
    name: "{{ nextcloud['OIDC']['client_id'] }}"
    description: Nextcloud client using user_oidc app.
    always_display_in_console: true
    protocol: openid-connect
    ######## Access settings ########
    root_url: https://{{ server['network']['domain_name'] }}
    base_url: https://{{ server['network']['domain_name'] }}
    redirect_uris:
      - /apps/user_oidc/code
    web_origins:
      - /*
    admin_url: https://{{ server['network']['domain_name'] }}
    ######## Capability config ########
    public_client: true
    standard_flow_enabled: true
    implicit_flow_enabled: false
    direct_access_grants_enabled: false
    service_accounts_enabled: true
    ######## Login settings ########
    consent_required: false
    authorization_services_enabled: false
    ######## Logout settings ########
    frontchannel_logout: false
    ######## Credentials ########
    client_authenticator_type: client-secret
    secret: "{{ nextcloud['OIDC']['client_secret'] }}"
    ######## Revocation ########
    not_before: "{{ ansible_date_time.epoch | default(0) }}"
    attributes:
      client.secret.creation.time: "{{ ansible_date_time.epoch | default(0) }}"
      ######## Logout settings ########
      backchannel.logout.session.required: "true"
      backchannel.logout.url: https://{{ server['network']['domain_name'] }}/apps/user_oidc/backchannel-logout/{{ nextcloud['OIDC']['identifier'] }}
      post.logout.redirect.uris: /
      ######## Login settings ########
      display.on.consent.screen: "false"
      #login_theme: ""
      #consent.screen.text:
    state: present
