---
- name: Generate self-signed certificates
  ansible.builtin.command: openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 365 -nodes -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.{{ server['network']['domain_name'] }}"
  args:
    chdir: "{{ containers['data_dir'] }}/nginx-proxy/"
  register: openssl
  failed_when: openssl.rc != 0
  become: true

- name: Enable certbot related systemd units
  ansible.builtin.systemd:
    name: "{{ item.name }}"
    scope: "{{ item.scope }}"
    enabled: true
    state: started
    daemon_reload: true
  become: "{{ item.su }}"
  loop:
    - { name: certbot.service, scope: user, su: false }
    - { name: certbot.timer, scope: user, su: false }
    - { name: nginx_cert_update.service, scope: system, su: true }
    - { name: nginx_cert_update.timer, scope: system, su: true }
