---
regex_server_ipv4: '{{ server["network"]["ipv4"] | regex_replace("\.", "\.") | regex_replace("[0-9]+$", "[0-9]+") }}'
regex_server_ipv6: "{{ server['network']['ipv6'] | regex_replace('[a-z0-9]+$', '[a-z0-9]+') }}"
regex_container_network: '{{ containers["loopback_network_address"] | regex_replace("\.", "\.") | regex_replace("[0-9]+$", "[0-9]+") }}'
