---
- name: Copy sshd_config to its respective place.
  ansible.builtin.copy:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: Reload ssh service
  become: true
