---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

header: false # Set to false to hide the header

footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

columns: "auto" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
# whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).
# You should set it to true when using an authentication proxy, it also reloads the page when a redirection is detected when checking connectivity.
connectivityCheck: true

# Optional: Proxy / hosting option
proxy:
  useCredentials: false # send cookies & authorization headers when fetching service specific data. Set to `true` if you use an authentication proxy. Can be overrided on service level.

# Set the default layout and color scheme
defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: auto # One of 'auto', 'light', or 'dark'

# Optional theming
theme: default # 'default' or one of the themes available in 'src/assets/themes'.

# Here is the exhaustive list of customization parameters
# However all value are optional and will fallback to default if not set.
# if you want to change only some of the colors, feel free to remove all unused key.
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#424242"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
    background-image: "assets/your/light/bg.png"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"
    background-image: "assets/your/dark/bg.png"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links: []

# Services
# First level array represents a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
{% if mailu['roundcube']['enabled'] is true %}
      - name: "Roundcube mail"
        subtitle: "Webmail"
        url: "https://mail.{{ server['network']['domain_name'] }}"
        logo: "assets/icons/Roundcube_logo.png"
        keywords: "email mail roundcube gmail"
        target: "_blank"
        tag: "app"
{% endif %}
{% if nextcloud['enabled'] is true %}
      - name: "Nextcloud"
        subtitle: "Cloud"
        url: "https://{{ server['network']['domain_name'] }}"
        logo: "assets/icons/nextcloud_logo.png"
        keywords: "nextcloud" # optional keyword used for searching purpose
        target: "_blank" # optional html tag target attribute
        tag: "app"
{% endif %}
{% if vaultwarden['enabled'] is true %}
      - name: "Vaultwarden"
        subtitle: "Password manager"
        url: "https://vault.{{ server['network']['domain_name'] }}"
        logo: "assets/icons/bitwarden_logo.png"
        keywords: "vaultwarden vault password bitwarden"
        target: "_blank"
        tag: "app"
{% endif %}

  - name: "Admin"
    icon: "fas fa-toolbox"
    items:
{% if collabora_office['enabled'] is true %}
      - name: "Collabora office Admin"
        subtitle: "Administration page of collabora office code server"
        url: "https://collaboraoffice.{{ server['network']['domain_name'] }}/browser/dist/admin/admin.html"
        logo: "assets/icons/collabora_logo.png"
        keywords: "Online Office collabora libreoffice"
        target: "_blank"
        tag: "admin"
{% endif %}
{% if vaultwarden['enabled'] is true %}
      - name: "Vaultwarden Admin"
        subtitle: "Administration page of Vaultwarden server"
        url: "https://vault.{{ server['network']['domain_name'] }}/admin"
        logo: "assets/icons/bitwarden_logo.png"
        keywords: "vaultwarden bitwarden"
        target: "_blank"
        tag: "admin"
{% endif %}
